//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatDetail
    {
        public int ChatDetailId { get; set; }
        public int ChatId { get; set; }
        public string Content { get; set; }
        public int Sender { get; set; }
        public System.DateTime SendTime { get; set; }
        public int ChatDetailStatus { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
