//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Likes = new HashSet<Like>();
        }
    
        public int CommentId { get; set; }
        public string CommentContent { get; set; }
        public string CommentImage { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> TimeLineDetailId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime CommentTime { get; set; }
        public int CommentStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Post Post { get; set; }
        public virtual TimeLineDetail TimeLineDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
    }
}
