//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forward
    {
        public int ForwardId { get; set; }
        public Nullable<int> SmallStepId { get; set; }
        public Nullable<int> SendStepId { get; set; }
        public int ReceiverStepId { get; set; }
        public int TypeSend { get; set; }
        public int ForwardStatus { get; set; }
    
        public virtual Step Step { get; set; }
        public virtual Step Step1 { get; set; }
        public virtual SmallStep SmallStep { get; set; }
    }
}
