//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChatDetail
    {
        public int GroupChatDetailId { get; set; }
        public int GroupChatMemberId { get; set; }
        public string GroupChatDetailContent { get; set; }
        public System.DateTime GroupChatDetailTime { get; set; }
        public int GroupChatMemberStatus { get; set; }
    
        public virtual GroupChatMember GroupChatMember { get; set; }
    }
}
