//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int LikeId { get; set; }
        public Nullable<int> CommentId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> TimeLineDetailId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int EmotionId { get; set; }
        public int LikeStatus { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Emotion Emotion { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Post Post { get; set; }
        public virtual TimeLineDetail TimeLineDetail { get; set; }
    }
}
