//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDiscussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberDiscussion()
        {
            this.ProjectDiscussions = new HashSet<ProjectDiscussion>();
        }
    
        public int MemberDiscussionId { get; set; }
        public int ProjectId { get; set; }
        public int ProjectMemberId { get; set; }
        public int EmployeeId { get; set; }
        public int MemberDiscussionStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectMember ProjectMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDiscussion> ProjectDiscussions { get; set; }
    }
}
