//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteId { get; set; }
        public string NoteContent { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> SmallStepMemberId { get; set; }
        public int NoteStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SmallStepMember SmallStepMember { get; set; }
    }
}
