//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int PlanId { get; set; }
        public string PlanContent { get; set; }
        public int GrantPermissionId { get; set; }
        public int PlanStatus { get; set; }
    
        public virtual GrantPermission GrantPermission { get; set; }
    }
}
