//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectMember()
        {
            this.MemberDiscussions = new HashSet<MemberDiscussion>();
            this.StepMembers = new HashSet<StepMember>();
        }
    
        public int ProjectMemberId { get; set; }
        public int ProjectId { get; set; }
        public int GrantPermissionId { get; set; }
        public int ProjectMemberStatus { get; set; }
    
        public virtual GrantPermission GrantPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberDiscussion> MemberDiscussions { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepMember> StepMembers { get; set; }
    }
}
