//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDiscussion
    {
        public int ProjectDiscussionId { get; set; }
        public int MemberDiscussionId { get; set; }
        public string DiscussionContent { get; set; }
        public int ProjectDiscussionStatus { get; set; }
    
        public virtual MemberDiscussion MemberDiscussion { get; set; }
    }
}
