//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WorkManagermentEntities : DbContext
    {
        public WorkManagermentEntities()
            : base("name=WorkManagermentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatDetail> ChatDetails { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<DepartmentEmployee> DepartmentEmployees { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Emotion> Emotions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Forward> Forwards { get; set; }
        public virtual DbSet<GrantPermission> GrantPermissions { get; set; }
        public virtual DbSet<GroupChatDetail> GroupChatDetails { get; set; }
        public virtual DbSet<GroupChatMember> GroupChatMembers { get; set; }
        public virtual DbSet<GroupChat> GroupChats { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<ManagerZone> ManagerZones { get; set; }
        public virtual DbSet<MemberDiscussion> MemberDiscussions { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<PostImage> PostImages { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<ProjectDiscussion> ProjectDiscussions { get; set; }
        public virtual DbSet<ProjectMember> ProjectMembers { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<Remind> Reminds { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SetPermission> SetPermissions { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<SmallStepComment> SmallStepComments { get; set; }
        public virtual DbSet<SmallStepMember> SmallStepMembers { get; set; }
        public virtual DbSet<SmallStepPriorityLevel> SmallStepPriorityLevels { get; set; }
        public virtual DbSet<SmallStep> SmallSteps { get; set; }
        public virtual DbSet<SmallStepWorkToDo> SmallStepWorkToDoes { get; set; }
        public virtual DbSet<StepMember> StepMembers { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeLineDetail> TimeLineDetails { get; set; }
        public virtual DbSet<TimeLineImage> TimeLineImages { get; set; }
        public virtual DbSet<TimeLine> TimeLines { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_getAllDepartmentByEmployeeId_Result> sp_getAllDepartmentByEmployeeId(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllDepartmentByEmployeeId_Result>("sp_getAllDepartmentByEmployeeId", soParameter);
        }
    
        public virtual ObjectResult<sp_GetAllEmployeeByDepartment_Result> sp_GetAllEmployeeByDepartment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllEmployeeByDepartment_Result>("sp_GetAllEmployeeByDepartment");
        }
    
        public virtual ObjectResult<string> sp_getAllPermissionsNameByRoleId(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getAllPermissionsNameByRoleId", soParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GetAllYEARByProjectType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetAllYEARByProjectType");
        }
    
        public virtual ObjectResult<sp_getEmployeeByDepartmentWhereDepartmentId_Result> sp_getEmployeeByDepartmentWhereDepartmentId(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmployeeByDepartmentWhereDepartmentId_Result>("sp_getEmployeeByDepartmentWhereDepartmentId", soParameter);
        }
    
        public virtual ObjectResult<sp_getEmployeeByDepartmentWhereEmployeeId_Result> sp_getEmployeeByDepartmentWhereEmployeeId(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmployeeByDepartmentWhereEmployeeId_Result>("sp_getEmployeeByDepartmentWhereEmployeeId", soParameter);
        }
    
        public virtual ObjectResult<sp_getEmployeeByDepartmentWhereEmployeeIds_Result> sp_getEmployeeByDepartmentWhereEmployeeIds(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmployeeByDepartmentWhereEmployeeIds_Result>("sp_getEmployeeByDepartmentWhereEmployeeIds", soParameter);
        }
    
        public virtual ObjectResult<sp_getEmployeeByRole_Result> sp_getEmployeeByRole()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmployeeByRole_Result>("sp_getEmployeeByRole");
        }
    
        public virtual ObjectResult<sp_getEmployeeByRoleByDepartment_Result> sp_getEmployeeByRoleByDepartment(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmployeeByRoleByDepartment_Result>("sp_getEmployeeByRoleByDepartment", soParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_getAllProjectDiscussionsByProjectId_Result> sp_getAllProjectDiscussionsByProjectId(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllProjectDiscussionsByProjectId_Result>("sp_getAllProjectDiscussionsByProjectId", soParameter);
        }
    
        public virtual ObjectResult<sp_GetAllEmployeeByProjectID_Result> sp_GetAllEmployeeByProjectID(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllEmployeeByProjectID_Result>("sp_GetAllEmployeeByProjectID", soParameter);
        }
    
        public virtual ObjectResult<sp_getAllEmployeeByRoleID_Result> sp_getAllEmployeeByRoleID(Nullable<int> so)
        {
            var soParameter = so.HasValue ?
                new ObjectParameter("so", so) :
                new ObjectParameter("so", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllEmployeeByRoleID_Result>("sp_getAllEmployeeByRoleID", soParameter);
        }
    
        public virtual ObjectResult<sp_getAllByProjectIdAndEmployeeId_Result> sp_getAllByProjectIdAndEmployeeId(Nullable<int> projectId, Nullable<int> employeeId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllByProjectIdAndEmployeeId_Result>("sp_getAllByProjectIdAndEmployeeId", projectIdParameter, employeeIdParameter);
        }
    }
}
