//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public int ShareId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> TimeLineId { get; set; }
        public Nullable<int> TimeLineDetailId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> PostId { get; set; }
        public int ShareType { get; set; }
        public int SharePrivacy { get; set; }
        public int ShareStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Group Group { get; set; }
        public virtual Post Post { get; set; }
        public virtual TimeLine TimeLine { get; set; }
        public virtual TimeLineDetail TimeLineDetail { get; set; }
    }
}
