//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmallStepPriorityLevel
    {
        public int SmallStepPriorityLevelId { get; set; }
        public string SmallStepPriorityLevelColor { get; set; }
        public int SmallStepId { get; set; }
        public int SmallStepPriorityLevelStatus { get; set; }
    
        public virtual SmallStep SmallStep { get; set; }
    }
}
