//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmallStepComment
    {
        public int SmallStepCommentId { get; set; }
        public string SmallStepCommentContent { get; set; }
        public string SmallStepCommentImage { get; set; }
        public int SmallStepId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime SmallStepCommentTime { get; set; }
        public int SmallStepCommentStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SmallStep SmallStep { get; set; }
    }
}
